-- Backfill for topics 1-2 sau khi V44 thay toan bo lesson/question nhung khong
-- gan lai vocabulary / question_vocabulary (bang noi dung SM-2 va tra-tu dung).
-- Xem chi tiet dieu tra trong buoi lam viec: 100% cau hoi topic 1-2 (149-164)
-- khong co lien ket question_vocabulary, va ~49 tu/cum tu moi trong noi dung
-- thay the chua ton tai trong bang vocabulary -> tinh nang cham-tra-nghia va
-- lich on SM-2 khong hoat dong cho hai topic nay.

-- =====================================================================
-- 1) Bo sung tu vung con thieu
-- =====================================================================
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'またね', NULL, 'mata ne', 'Hẹn gặp lại (thân mật)', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'また明日', 'またあした', 'mata ashita', 'Hẹn gặp lại vào ngày mai', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'じゃあね', NULL, 'jaa ne', 'Tạm biệt nhé (rất thân mật)', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'お休みなさい', 'おやすみなさい', 'oyasuminasai', 'Chúc ngủ ngon', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', '失礼します', 'しつれいします', 'shitsurei shimasu', 'Xin phép, tôi xin cáo lui (trang trọng)', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'お疲れ様です', 'おつかれさまです', 'otsukaresama desu', 'Cảm ơn vì đã vất vả (chào khi tan làm/gặp đồng nghiệp)', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'お先に失礼します', 'おさきにしつれいします', 'osaki ni shitsurei shimasu', 'Xin phép tôi về trước', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'お元気ですか', 'おげんきですか', 'ogenki desu ka', 'Bạn khoẻ không?', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', '元気です', 'げんきです', 'genki desu', 'Tôi khoẻ', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'まあまあです', NULL, 'maamaa desu', 'Cũng tạm ổn', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'おはよう。お元気ですか', 'おはよう。おげんきですか', 'ohayou. ogenki desu ka.', 'Chào buổi sáng. Bạn khoẻ không?', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'こんにちは。元気です', 'こんにちは。げんきです', 'konnichiwa. genki desu.', 'Chào (buổi trưa). Tôi khoẻ.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'いってきます。いってらっしゃい', NULL, 'itte kimasu. itte rasshai.', 'Con đi đây. / Đi cẩn thận nhé.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'さようなら。またね', NULL, 'sayounara. mata ne.', 'Tạm biệt. Hẹn gặp lại.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('VOCAB', 'お茶', 'おちゃ', 'ocha', 'Trà', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('VOCAB', 'ご飯', 'ごはん', 'gohan', 'Cơm', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('VOCAB', '水', 'みず', 'mizu', 'Nước', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'お茶をください', 'おちゃをください', 'ocha o kudasai', 'Cho tôi (xin) trà.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'ご飯をください', 'ごはんをください', 'gohan o kudasai', 'Cho tôi xin cơm.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('VOCAB', '寿司', 'すし', 'sushi', 'Sushi', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('VOCAB', '肉', 'にく', 'niku', 'Thịt', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('VOCAB', '魚', 'さかな', 'sakana', 'Cá', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', '寿司をください', 'すしをください', 'sushi o kudasai', 'Cho tôi xin sushi.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', '魚をください', 'さかなをください', 'sakana o kudasai', 'Cho tôi xin cá.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'お願いします', 'おねがいします', 'onegaishimasu', 'Làm ơn / xin nhờ (lịch sự hơn kudasai)', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'ラーメンをお願いします', 'ラーメンをおねがいします', 'raamen o onegaishimasu', 'Cho tôi ramen (lịch sự).', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('VOCAB', '卵', 'たまご', 'tamago', 'Trứng', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('VOCAB', '野菜', 'やさい', 'yasai', 'Rau', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'メニューをお願いします', 'メニューをおねがいします', 'menyuu o onegaishimasu', 'Cho tôi xem thực đơn.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', '卵と野菜をください', 'たまごとやさいをください', 'tamago to yasai o kudasai', 'Cho tôi trứng và rau.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'すみません、メニューをください', NULL, 'sumimasen, menyuu o kudasai.', 'Xin lỗi, cho tôi xin thực đơn.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'これはいくらですか', NULL, 'kore wa ikura desu ka', 'Cái này bao nhiêu tiền?', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('VOCAB', '注文', 'ちゅうもん', 'chuumon', 'Gọi món / đặt hàng', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', '注文をお願いします', 'ちゅうもんをおねがいします', 'chuumon o onegaishimasu', 'Tôi muốn đặt món.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'お会計をお願いします', 'おかいけいをおねがいします', 'okaikei o onegaishimasu', 'Cho tôi tính tiền.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'すみません、お会計をお願いします', 'すみません、おかいけいをおねがいします', 'sumimasen, okaikei o onegaishimasu.', 'Xin lỗi, cho tôi tính tiền.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'お茶と寿司をください', 'おちゃとすしをください', 'ocha to sushi o kudasai', 'Cho tôi trà và sushi.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'ご飯と魚をください', 'ごはんとさかなをください', 'gohan to sakana o kudasai', 'Cho tôi cơm và cá.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'ラーメンと野菜をお願いします', 'ラーメンとやさいをおねがいします', 'raamen to yasai o onegaishimasu', 'Cho tôi ramen và rau.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', '卵と水をください', 'たまごとみずをください', 'tamago to mizu o kudasai', 'Cho tôi trứng và nước.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', '肉とご飯をください', 'にくとごはんをください', 'niku to gohan o kudasai', 'Cho tôi thịt và cơm.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'すみません、メニューをお願いします', 'すみません、メニューをおねがいします', 'sumimasen, menyuu o onegaishimasu', 'Xin lỗi, cho tôi xem thực đơn.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', '寿司はいくらですか', 'すしはいくらですか', 'sushi wa ikura desu ka', 'Sushi bao nhiêu tiền?', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'お茶とご飯とパンをください', 'おちゃとごはんとパンをください', 'ocha to gohan to pan o kudasai', 'Cho tôi trà, cơm và bánh mì.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'すみません、水をください', 'すみません、みずをください', 'sumimasen, mizu o kudasai.', 'Xin lỗi, cho tôi xin nước.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', '卵と魚をください', 'たまごとさかなをください', 'tamago to sakana o kudasai', 'Cho tôi trứng và cá.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'お茶とパンをください', 'おちゃとパンをください', 'ocha to pan o kudasai', 'Cho tôi trà và bánh mì.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', 'ご飯と魚と野菜を注文します', 'ごはんとさかなとやさいをちゅうもんします', 'gohan to sakana to yasai o chuumon shimasu', 'Cho tôi gọi món: cơm, cá và rau.', 'N5');
INSERT INTO vocabulary (item_type, surface, reading, romaji, meaning_vn, jlpt_level) VALUES ('PHRASE', '水をください', 'みずをください', 'mizu o kudasai', 'Cho tôi xin nước.', 'N5');

-- =====================================================================
-- 2) Gan lai question_vocabulary (is_target = TRUE) cho tung cau hoi
--    theo dung tu/cum tu ma cau hoi do kiem tra.
-- =====================================================================
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1980, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おはようございます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1987, v.id, TRUE FROM vocabulary v WHERE v.surface = 'また明日' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1996, v.id, TRUE FROM vocabulary v WHERE v.surface = 'いってきます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2006, v.id, TRUE FROM vocabulary v WHERE v.surface = 'いただきます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2007, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ごちそうさまでした' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2014, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おはよう' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2014, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お元気ですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2017, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お元気ですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2021, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お元気ですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2025, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お疲れ様です' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2032, v.id, TRUE FROM vocabulary v WHERE v.surface = 'また明日' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2044, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おはようございます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2049, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お元気ですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2051, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ごちそうさまでした' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2064, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2064, v.id, TRUE FROM vocabulary v WHERE v.surface = 'と' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2064, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ご飯' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2067, v.id, TRUE FROM vocabulary v WHERE v.surface = '水をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2073, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ジュース' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2073, v.id, TRUE FROM vocabulary v WHERE v.surface = 'を' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2073, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2077, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ラーメンをお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2083, v.id, TRUE FROM vocabulary v WHERE v.surface = '卵' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2083, v.id, TRUE FROM vocabulary v WHERE v.surface = 'と' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2083, v.id, TRUE FROM vocabulary v WHERE v.surface = '野菜' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2089, v.id, TRUE FROM vocabulary v WHERE v.surface = 'これはいくらですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2097, v.id, TRUE FROM vocabulary v WHERE v.surface = 'コーヒー' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2097, v.id, TRUE FROM vocabulary v WHERE v.surface = 'と' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2097, v.id, TRUE FROM vocabulary v WHERE v.surface = 'パン' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2097, v.id, TRUE FROM vocabulary v WHERE v.surface = 'を' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2097, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2103, v.id, TRUE FROM vocabulary v WHERE v.surface = '寿司はいくらですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2106, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ラーメンをお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2110, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お会計をお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2113, v.id, TRUE FROM vocabulary v WHERE v.surface = 'これはいくらですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2119, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2119, v.id, TRUE FROM vocabulary v WHERE v.surface = 'と' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2119, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ご飯' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2131, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ジュース' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2131, v.id, TRUE FROM vocabulary v WHERE v.surface = 'を' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2131, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2136, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ラーメンをお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2138, v.id, TRUE FROM vocabulary v WHERE v.surface = 'これはいくらですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1968, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おはよう' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1969, v.id, TRUE FROM vocabulary v WHERE v.surface = 'こんにちは' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1970, v.id, TRUE FROM vocabulary v WHERE v.surface = 'こんばんは' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1971, v.id, TRUE FROM vocabulary v WHERE v.surface = 'さようなら' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1972, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おはよう' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1973, v.id, TRUE FROM vocabulary v WHERE v.surface = 'こんばんは' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1974, v.id, TRUE FROM vocabulary v WHERE v.surface = 'さようなら' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1975, v.id, TRUE FROM vocabulary v WHERE v.surface = 'こんにちは' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1976, v.id, TRUE FROM vocabulary v WHERE v.surface = 'またね' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1977, v.id, TRUE FROM vocabulary v WHERE v.surface = 'またね' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1978, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おはようございます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1979, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おはようございます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1981, v.id, TRUE FROM vocabulary v WHERE v.surface = 'また明日' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1982, v.id, TRUE FROM vocabulary v WHERE v.surface = 'また明日' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1983, v.id, TRUE FROM vocabulary v WHERE v.surface = 'じゃあね' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1984, v.id, TRUE FROM vocabulary v WHERE v.surface = 'じゃあね' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1985, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お休みなさい' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1986, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お休みなさい' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1988, v.id, TRUE FROM vocabulary v WHERE v.surface = '失礼します' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1989, v.id, TRUE FROM vocabulary v WHERE v.surface = '失礼します' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1990, v.id, TRUE FROM vocabulary v WHERE v.surface = 'いってきます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1991, v.id, TRUE FROM vocabulary v WHERE v.surface = 'いってらっしゃい' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1992, v.id, TRUE FROM vocabulary v WHERE v.surface = 'いってきます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1993, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ただいま' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1994, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ただいま' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1995, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おかえりなさい' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1997, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おかえりなさい' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1998, v.id, TRUE FROM vocabulary v WHERE v.surface = 'いただきます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 1999, v.id, TRUE FROM vocabulary v WHERE v.surface = 'いただきます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2000, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ごちそうさまでした' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2001, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ごちそうさまでした' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2002, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ごちそうさまでした' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2003, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お疲れ様です' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2004, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お疲れ様です' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2005, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お先に失礼します' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2008, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お元気ですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2009, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お元気ですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2010, v.id, TRUE FROM vocabulary v WHERE v.surface = '元気です' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2011, v.id, TRUE FROM vocabulary v WHERE v.surface = '元気です' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2012, v.id, TRUE FROM vocabulary v WHERE v.surface = 'まあまあです' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2013, v.id, TRUE FROM vocabulary v WHERE v.surface = 'まあまあです' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2015, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おはよう。お元気ですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2016, v.id, TRUE FROM vocabulary v WHERE v.surface = 'こんにちは。元気です' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2018, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ただいま' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2019, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おかえりなさい' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2020, v.id, TRUE FROM vocabulary v WHERE v.surface = 'いってきます。いってらっしゃい' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2022, v.id, TRUE FROM vocabulary v WHERE v.surface = '元気です' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2023, v.id, TRUE FROM vocabulary v WHERE v.surface = 'こんばんは' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2024, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お先に失礼します' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2026, v.id, TRUE FROM vocabulary v WHERE v.surface = 'また明日' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2027, v.id, TRUE FROM vocabulary v WHERE v.surface = 'さようなら。またね' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2028, v.id, TRUE FROM vocabulary v WHERE v.surface = 'こんにちは' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2029, v.id, TRUE FROM vocabulary v WHERE v.surface = 'こんばんは' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2030, v.id, TRUE FROM vocabulary v WHERE v.surface = 'さようなら' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2031, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おはようございます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2033, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お休みなさい' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2034, v.id, TRUE FROM vocabulary v WHERE v.surface = 'いってらっしゃい' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2035, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ただいま' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2036, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お疲れ様です' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2037, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ごちそうさまでした' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2038, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お元気ですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2039, v.id, TRUE FROM vocabulary v WHERE v.surface = 'まあまあです' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2040, v.id, TRUE FROM vocabulary v WHERE v.surface = 'こんにちは' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2041, v.id, TRUE FROM vocabulary v WHERE v.surface = 'さようなら' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2042, v.id, TRUE FROM vocabulary v WHERE v.surface = 'またね' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2043, v.id, TRUE FROM vocabulary v WHERE v.surface = '失礼します' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2045, v.id, TRUE FROM vocabulary v WHERE v.surface = 'じゃあね' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2046, v.id, TRUE FROM vocabulary v WHERE v.surface = 'いってらっしゃい' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2047, v.id, TRUE FROM vocabulary v WHERE v.surface = 'おかえりなさい' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2048, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お先に失礼します' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2050, v.id, TRUE FROM vocabulary v WHERE v.surface = '元気です' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2052, v.id, TRUE FROM vocabulary v WHERE v.surface = 'いただきます' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2053, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お疲れ様です' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2054, v.id, TRUE FROM vocabulary v WHERE v.surface = 'さようなら。またね' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2055, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2056, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ご飯' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2057, v.id, TRUE FROM vocabulary v WHERE v.surface = '水' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2058, v.id, TRUE FROM vocabulary v WHERE v.surface = 'パン' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2059, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2060, v.id, TRUE FROM vocabulary v WHERE v.surface = 'コーヒー' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2061, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ご飯' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2062, v.id, TRUE FROM vocabulary v WHERE v.surface = '水' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2063, v.id, TRUE FROM vocabulary v WHERE v.surface = 'パン' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2065, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2066, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ご飯をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2068, v.id, TRUE FROM vocabulary v WHERE v.surface = '寿司' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2069, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ジュース' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2070, v.id, TRUE FROM vocabulary v WHERE v.surface = '肉' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2071, v.id, TRUE FROM vocabulary v WHERE v.surface = '魚' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2072, v.id, TRUE FROM vocabulary v WHERE v.surface = '寿司をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2074, v.id, TRUE FROM vocabulary v WHERE v.surface = '魚をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2075, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2076, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ラーメンをお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2078, v.id, TRUE FROM vocabulary v WHERE v.surface = '卵' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2079, v.id, TRUE FROM vocabulary v WHERE v.surface = '野菜' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2080, v.id, TRUE FROM vocabulary v WHERE v.surface = 'メニュー' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2081, v.id, TRUE FROM vocabulary v WHERE v.surface = 'メニューをお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2082, v.id, TRUE FROM vocabulary v WHERE v.surface = 'メニューをお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2084, v.id, TRUE FROM vocabulary v WHERE v.surface = '卵と野菜をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2085, v.id, TRUE FROM vocabulary v WHERE v.surface = 'すみません' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2086, v.id, TRUE FROM vocabulary v WHERE v.surface = 'すみません、メニューをください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2087, v.id, TRUE FROM vocabulary v WHERE v.surface = 'これはいくらですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2088, v.id, TRUE FROM vocabulary v WHERE v.surface = 'これはいくらですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2090, v.id, TRUE FROM vocabulary v WHERE v.surface = '注文' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2091, v.id, TRUE FROM vocabulary v WHERE v.surface = '注文をお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2092, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お会計をお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2093, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お会計をお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2094, v.id, TRUE FROM vocabulary v WHERE v.surface = 'すみません、お会計をお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2095, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶と寿司をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2096, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ご飯と魚をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2098, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ラーメンと野菜をお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2099, v.id, TRUE FROM vocabulary v WHERE v.surface = '卵と水をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2100, v.id, TRUE FROM vocabulary v WHERE v.surface = '肉とご飯をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2101, v.id, TRUE FROM vocabulary v WHERE v.surface = 'すみません、メニューをお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2102, v.id, TRUE FROM vocabulary v WHERE v.surface = '寿司はいくらですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2104, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶とご飯とパンをください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2105, v.id, TRUE FROM vocabulary v WHERE v.surface = 'すみません、水をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2107, v.id, TRUE FROM vocabulary v WHERE v.surface = 'メニューをお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2108, v.id, TRUE FROM vocabulary v WHERE v.surface = 'これはいくらですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2109, v.id, TRUE FROM vocabulary v WHERE v.surface = '卵と魚をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2111, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶とパンをください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2112, v.id, TRUE FROM vocabulary v WHERE v.surface = 'すみません、お会計をお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2114, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ご飯と魚と野菜を注文します' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2115, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2116, v.id, TRUE FROM vocabulary v WHERE v.surface = '水' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2117, v.id, TRUE FROM vocabulary v WHERE v.surface = 'パン' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2118, v.id, TRUE FROM vocabulary v WHERE v.surface = '水をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2120, v.id, TRUE FROM vocabulary v WHERE v.surface = '魚をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2121, v.id, TRUE FROM vocabulary v WHERE v.surface = 'メニュー' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2122, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ラーメンをお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2123, v.id, TRUE FROM vocabulary v WHERE v.surface = '卵と野菜をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2124, v.id, TRUE FROM vocabulary v WHERE v.surface = 'これはいくらですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2125, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お会計をお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2126, v.id, TRUE FROM vocabulary v WHERE v.surface = 'すみません' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2127, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2128, v.id, TRUE FROM vocabulary v WHERE v.surface = '水' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2129, v.id, TRUE FROM vocabulary v WHERE v.surface = '寿司' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2130, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2132, v.id, TRUE FROM vocabulary v WHERE v.surface = '野菜' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2133, v.id, TRUE FROM vocabulary v WHERE v.surface = '卵' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2134, v.id, TRUE FROM vocabulary v WHERE v.surface = 'これはいくらですか' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2135, v.id, TRUE FROM vocabulary v WHERE v.surface = '注文をお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2137, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶と寿司をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2139, v.id, TRUE FROM vocabulary v WHERE v.surface = 'ご飯と魚をください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2140, v.id, TRUE FROM vocabulary v WHERE v.surface = 'すみません、お会計をお願いします' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
INSERT IGNORE INTO question_vocabulary (question_id, vocabulary_id, is_target) SELECT 2141, v.id, TRUE FROM vocabulary v WHERE v.surface = 'お茶とご飯とパンをください' AND v.item_type <> 'KANA' ORDER BY v.id DESC LIMIT 1;
